name: Compile & MTR

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**.md'
      - 'scripts/setup/**'
      - '.devcontainer/**'
  pull_request:
    branches-ignore:
      - main
        # wait for mergify to ignore
        #paths-ignore:
            #- 'Docs/**'
            #- 'website/**'
            #- '**.md'
            #- 'scripts/**'
            #- 'install_scripts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc


jobs:
  stonedb-build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install cmake make perl bison libaio-dev \
          openssl libssl-dev libncurses5-dev libreadline-dev \
          autoconf automake libtool \
          libreadline-dev libpam0g-dev zlib1g-dev libcurl-ocaml-dev \
          autotools-dev libicu-dev libboost-all-dev \
          libgflags-dev libsnappy-dev libbz2-dev liblz4-dev libzstd-dev libjemalloc-dev -y
          
      - name: install libs
        run: |
          sudo git clone https://github.com/hustjieke/stonedb-libs.git
          cd stonedb-libs
          sudo tar -zxvf stonedb-boost.tar.gz
          sudo tar -zxvf stonedb-gcc-rocksdb.tar.gz
          sudo tar -zxvf stonedb-marisa.tar.gz
          cd gcc7.3
          sudo tar -zxvf bin.tar.gz
          sudo tar -zxvf include.tar.gz
          sudo tar -zxvf lib64.tar.gz
          sudo tar -zxvf lib.tar.gz
          sudo tar -zxvf share.tar.gz
          cd libexec/gcc/x86_64-pc-linux-gnu/7.3.0
          sudo tar -zxvf all.tar.gz
          sudo tar -zxvf cc1plus.tar.gz
          sudo tar -zxvf cc1.tar.gz
          cd - && cd ..
          sudo cp -r stonedb-boost /usr/local/stonedb-boost
          sudo cp -r stonedb-boost/lib /usr/local/stonedb-boost/include
          sudo cp -r stonedb-gcc-rocksdb /usr/local/stonedb-gcc-rocksdb
          sudo cp -r stonedb-marisa /usr/local/stonedb-marisa
          sudo cp -r gcc7.3 /usr/local/gcc7.3
          sudo rm /usr/bin/gcc
          sudo ln -s /usr/local/gcc7.3/bin/gcc /usr/bin/gcc
          sudo rm /usr/bin/g++
          sudo ln -s /usr/local/gcc7.3/bin/g++ /usr/bin/g++
          sudo rm /usr/bin/c++
          sudo ln -s /usr/local/gcc7.3/bin/c++ /usr/bin/c++
          cd ..
       
      - name: compile stonedb
        run: |
          sudo cmake ./ \
          -DCMAKE_BUILD_TYPE=release \
          -DCMAKE_INSTALL_PREFIX=/stonedb57/install \
          -DMYSQL_DATADIR=/stonedb57/install/data \
          -DSYSCONFDIR=/stonedb57/install \
          -DMYSQL_UNIX_ADDR=/stonedb57/install/tmp/mysql.sock \
          -DWITH_EMBEDDED_SERVER=OFF \
          -DWITH_STONEDB_STORAGE_ENGINE=1 \
          -DWITH_MYISAM_STORAGE_ENGINE=1 \
          -DWITH_INNOBASE_STORAGE_ENGINE=1 \
          -DWITH_PARTITION_STORAGE_ENGINE=1 \
          -DMYSQL_TCP_PORT=3306 \
          -DENABLED_LOCAL_INFILE=1 \
          -DEXTRA_CHARSETS=all \
          -DDEFAULT_CHARSET=utf8 \
          -DDEFAULT_COLLATION=utf8_general_ci \
          -DWITH_BOOST=/usr/local/stonedb-boost/include
          sudo make VERBOSE=1 -j`nproc`
          sudo make install -j`nproc`

          #- name: mtr test
          #  run: |
          #    sudo mkdir -p /stonedb57/install/data/innodb
          #    sudo mkdir -p /stonedb57/install/binlog
          #    sudo mkdir -p /stonedb5 7/install/log
          #    sudo mkdir -p /stonedb57/install/tmp
          #    sudo chown -R mysql:mysql /stonedb57
          #    cd /stonedb57/install/mysql-test
          #    sudo ./mysql-test-run.pl --suite=stonedb --nowarnings --force
          
      - name: pack stonedb after install
        run: sudo tar zcvf ./stonedb57.tar.gz /stonedb57
      
      - uses: actions/upload-artifact@v3
        with:
          name: stonedb-artifact
          path: ./stonedb57.tar.gz
